Token impl
PokemonGoers/PokeData pull request #193
Opened 2016-11-02 22:54 UTC by jonas-he

2016-11-02 23:17 UTC, sacdallago requested changes

2016-11-02 23:17 UTC, sacdallago commented on config.js
> +    "token" : "hastobefilledwithsupersecrettoken", //please choose secret token and communicate it privately
Can you please make this env variable dependent? Docker will build yes or yes and it's hard to intervene in the config.json programmatically inside the docker container

2016-11-02 23:43 UTC, jonas-he commented
@sacdallago done, env variable is called `API_TOKEN`

2016-11-03 00:40 UTC, sacdallago commented
Sorry for bothering on this, but you'll need to define a fallback as well ( `|| "abc"`) otherwise your code will yield unexpected behaviors

2016-11-03 09:57 UTC, jonas-he commented
@sacdallago done

2016-11-03 17:01 UTC, sacdallago approved these changes

2016-11-03 17:18 UTC, merged